"""initial tables: project, paper, search_query, screening_decision

Revision ID: 5a8685c38c5a
Revises: 
Create Date: 2026-07-07 16:46:55.746106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a8685c38c5a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('proposal_text', sa.Text(), nullable=True),
    sa.Column('protocol', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('paper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('title_normalized', sa.String(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('authors', sa.JSON(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('arxiv_id', sa.String(), nullable=True),
    sa.Column('s2_id', sa.String(), nullable=True),
    sa.Column('ntrs_id', sa.String(), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_arxiv_id'), 'paper', ['arxiv_id'], unique=False)
    op.create_index(op.f('ix_paper_doi'), 'paper', ['doi'], unique=False)
    op.create_index('ix_paper_project_status', 'paper', ['project_id', 'status'], unique=False)
    op.create_index(op.f('ix_paper_title_normalized'), 'paper', ['title_normalized'], unique=False)
    op.create_table('search_query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('screening_decision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screening_decision_paper_id'), 'screening_decision', ['paper_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screening_decision_paper_id'), table_name='screening_decision')
    op.drop_table('screening_decision')
    op.drop_table('search_query')
    op.drop_index(op.f('ix_paper_title_normalized'), table_name='paper')
    op.drop_index('ix_paper_project_status', table_name='paper')
    op.drop_index(op.f('ix_paper_doi'), table_name='paper')
    op.drop_index(op.f('ix_paper_arxiv_id'), table_name='paper')
    op.drop_table('paper')
    op.drop_table('project')
    # ### end Alembic commands ###
